package com.example.mymovie.model

data class Movie(val id: String,
                val title: String,
                val year: String,
                val genre: String,
                 val director: String,
                 val actors: String,
                 val plot: String,
                 val poster: String,
                 val images: List<String>,
                 val rating: String
                 )

fun getMovies(): List<Movie> {
    return listOf(

        Movie(id = "1",
            title = "Interstellar",
            year = "2014",
            genre = "Adventure, Drama, Sci-Fi",
            director = "Christopher Nolan",
            actors = "Ellen Burstyn, Matthew McConaughey, Mackenzie Foy, John Lithgow",
            plot = "A team of explorers travel through a wormhole in space in an attempt to ensure humanity's survival.",
            poster = "https://m.media-amazon.com/images/I/A1JVqNMI7UL._SL1500_.jpg",
            images = listOf(
                "https://images-na.ssl-images-amazon.com/images/M/MV5BMjA3NTEwOTMxMV5BMl5BanBnXkFtZTgwMjMyODgxMzE@._V1_SX1500_CR0,0,1500,999_AL_.jpg",
                "https://images-na.ssl-images-amazon.com/images/M/MV5BMzQ5ODE2MzEwM15BMl5BanBnXkFtZTgwMTMyODgxMzE@._V1_SX1500_CR0,0,1500,999_AL_.jpg",
                "https://images-na.ssl-images-amazon.com/images/M/MV5BMTg4Njk4MzY0Nl5BMl5BanBnXkFtZTgwMzIyODgxMzE@._V1_SX1500_CR0,0,1500,999_AL_.jpg",
                "https://images-na.ssl-images-amazon.com/images/M/MV5BMzE3MTM0MTc3Ml5BMl5BanBnXkFtZTgwMDIyODgxMzE@._V1_SX1500_CR0,0,1500,999_AL_.jpg",
                "https://images-na.ssl-images-amazon.com/images/M/MV5BNjYzNjE2NDk3N15BMl5BanBnXkFtZTgwNzEyODgxMzE@._V1_SX1500_CR0,0,1500,999_AL_.jpg"),
            rating = "8.6"),

        Movie(id = "2",
            title = "Iron Man",
            year = "2008",
            genre = "Action, Adventure, Sci-Fi",
            director ="Jon Favreau",
            actors = "Robert Downey Jr., Gwyneth Paltrow, Terrence Howard",
            plot = "After being held captive in an Afghan cave, billionaire engineer Tony Stark creates a unique weaponized suit of armor to fight evil.",
            poster = "https://static.wikia.nocookie.net/marvelcinematicuniverse/images/1/1e/Iron_Man_Official_Poster.jpg/revision/latest/scale-to-width-down/864?cb=20120115035645",
            images = listOf(
                "https://static.wikia.nocookie.net/marvelcinematicuniverse/images/9/9d/Tumblr_l1iotoYo541qbn8c7.jpg/revision/latest/scale-to-width-down/1000?cb=20141129031517",
                "https://static.wikia.nocookie.net/marvelcinematicuniverse/images/f/f8/Stark_and_Yinsen.jpg/revision/latest/scale-to-width-down/1000?cb=20141129031735",
                "https://static.wikia.nocookie.net/marvelcinematicuniverse/images/5/5a/Tony-stark-and-pepper-potts-for-the-iron-man-movie.jpg/revision/latest/scale-to-width-down/1000?cb=20141129033228",
                "https://static.wikia.nocookie.net/marvelcinematicuniverse/images/4/41/Iron_Man_Mark_III_in_Flight.jpg/revision/latest/scale-to-width-down/570?cb=20140906060402",
                "https://static.wikia.nocookie.net/marvelcinematicuniverse/images/a/a6/Iron_Monger_v._Iron_Man.jpg/revision/latest/scale-to-width-down/1000?cb=20141129040501"),
            rating = "7.9"),

        Movie(id = "3",
            title = "Batman Begins",
            year = "2005",
            genre = "Action, Crime, Drama",
            director ="Christopher Nolan",
            actors = "Christian Bale, Katie Holmes, Michael Caine, Liam Neeson",
            plot = "After training with his mentor, Batman begins his fight to free crime-ridden Gotham City from corruption.",
            poster = "https://upload.wikimedia.org/wikipedia/en/a/af/Batman_Begins_Poster.jpg",
            images = listOf(
                "https://irs.www.warnerbros.com/gallery-v2-tablet-jpeg/batman_begins_photo_21-567301061.jpg",
                "https://irs.www.warnerbros.com/gallery-v2-tablet-jpeg/batman_begins_photo_11-556669628.jpg",
                "https://irs.www.warnerbros.com/gallery-v2-tablet-jpeg/batman_begins_photo_51-717048823.jpg",
                "https://irs.www.warnerbros.com/gallery-v2-tablet-jpeg/batman_begins_photo_29-1264171951.jpg",
                "https://irs.www.warnerbros.com/gallery-v2-tablet-jpeg/batman_begins_photo_8-1244928657.jpg",
                "https://irs.www.warnerbros.com/gallery-v2-tablet-jpeg/batman_begins_photo_5-633064999.jpg",
                "https://miro.medium.com/max/1400/1*bEG4nXLcAvvtAXFJ4w_sIQ.jpeg"),
            rating = "8.2"),

        Movie(id = "4",
            title = "The Shawshank Redemption",
            year = "1994",
            genre = "Drama",
            director ="Christopher Nolan",
            actors = "Tim Robbins, Morgan Freeman",
            plot = "Two imprisoned men bond over a number of years, finding solace and eventual redemption through acts of common decency.",
            poster = "https://m.media-amazon.com/images/M/MV5BMDFkYTc0MGEtZmNhMC00ZDIzLWFmNTEtODM1ZmRlYWMwMWFmXkEyXkFqcGdeQXVyMTMxODk2OTU@._V1_FMjpg_UX1000_.jpg",
            images = listOf(
                "https://content.internetvideoarchive.com/content/hdphotos/127/000127/000127_796x448_5349_045.jpg",
                "https://www.slashfilm.com/img/gallery/the-deleted-shawshank-redemption-scenes-youve-likely-never-seen/l-intro-1642184743.jpg",
                "https://media2.clevescene.com/clevescene/imager/u/original/29548898/shaw.jpg",
                "https://c.tenor.com/lMhOnj22y9kAAAAC/the-shawshank-redemption.gif",
                "https://img-9gag-fun.9cache.com/photo/a27XMY9_460s.jpg",
                "https://m.media-amazon.com/images/M/MV5BMTgxMTU1MDkwOV5BMl5BanBnXkFtZTcwMDQxNDY3Mw@@._V1_.jpg",
                "https://i.pinimg.com/originals/6e/50/fc/6e50fc88ac154b828641d83ad62247c9.jpg",
                "https://i.ytimg.com/vi/7GxgyzwJ4Do/maxresdefault.jpg"),
            rating = "9.3"),

        Movie(id = "5",
            title = "The Pursuit of Happyness",
            year = "2006",
            genre = "Biography, Drama",
            director = "Gabriele Muccino",
            actors = "Will Smith, Thandiwe Newton, Jaden Smith",
            plot = "A struggling salesman takes custody of his son as he's poised to begin a life-changing professional career.",
            poster = "https://www.sonypictures.com/sites/default/files/styles/max_560x840/public/title-key-art/thepursuitofhappyness_onesheet_1400x2100.png?itok=BSpvsOsJ",
            images = listOf(
                "https://m.media-amazon.com/images/M/MV5BNzQ1ODY2MTk3Ml5BMl5BanBnXkFtZTcwMzA1NjYyMw@@._V1_.jpg",
                "https://occ-0-2794-2219.1.nflxso.net/dnm/api/v6/6AYY37jfdO6hpXcMjf9Yu5cnmO0/AAAABUoWmM3vDOMzh3eO7AOrWMukSG7R-8bWs_EMiv0ltor5ZoduZzTH9a_e2YE86H9AgyNZyUl4RvILUwXTJT4O-efAeC_m.jpg?r=6f3",
                "https://c8.alamy.com/comp/GHF5XT/das-streben-nach-glck-the-pursuit-of-happyness-usa-2006-gabriele-muccino-GHF5XT.jpg",
                "https://resizing.flixster.com/KNd-8V8D76om-P-1dF0pOemqVSA=/740x380/v2/https://statcdn.fandango.com/MPX/image/NBCU_Fandango/828/163/21847.png",
                "https://i.pinimg.com/736x/4c/af/e1/4cafe1be623cbbbf935c805d644d7de2--the-pursuit-of-happyness-pursuit-of-happiness.jpg"),
            rating = "8.0"),

        Movie(id = "6",
            title = "Avengers: Endgame",
            year = "2019",
            genre = "Action, Adventure, Drama",
            director = "Anthony Russo, Joe Russo",
            actors = "Robert Downey Jr., Chris Evans, Mark Ruffalo, Chris Hemsworth, Scarlett Johansson, Jeremy Renner, Benedict Cmberbatch, Chadwick Boseman, Tom Holland, Brie Larson, Elizabeth Olsen",
            plot = "After the devastating events of Avengers: Infinity War (2018), the universe is in ruins. With the help of remaining allies, the Avengers assemble once more in order to reverse Thanos' actions and restore balance to the universe.",
            poster = "https://terrigen-cdn-dev.marvel.com/content/prod/1x/avengersendgame_lob_crd_05.jpg",
            images = listOf(
                "https://www.screengeek.net/wp-content/uploads/2019/08/avengers-endgame-thanos.jpg",
                "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcReGi0RLj20UIJVofH8RGaNZcR0Y0g6vXXqng&usqp=CAU",
                "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTu4oFoFqdOtc2ksR7aSphxuQd8w2IabgesGA&usqp=CAU",
                "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRGbo5DO7Pg0QmcxMMP-pmGAjh3u6K6kFac0A&usqp=CAU",
                "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcT1sPpgTHT4V1JK8JlOix0XSSTQsMo1PPWAMg&usqp=CAU",
                "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTkFLxD0dYs2e5tpW4TKRPEob1s-Bj-VctOtg&usqp=CAU"),
            rating = "8.4"),

        Movie(id = "7",
            title = "Fast and Furious 7",
            year = "2015",
            genre = "Action, Crime, Thriller",
            director = "James Wan",
            actors = "Vin Diesel, Paul Walker, Jason Statham, Michelle Rodriguez, Dwayne Johnson, Jordana Brewster, Tyrese Gibson, Ludacris",
            plot = "Deckard Shaw seeks revenge against Dominic Toretto and his family for his comatose brother.",
            poster = "https://static.wikia.nocookie.net/fastandfurious/images/a/aa/FF7_officialposter.jpg/revision/latest/scale-to-width-down/1000?cb=20200323092117",
            images = listOf(
                "https://static.wikia.nocookie.net/fastandfurious/images/3/39/Paul_Walker_Facial_Recreation_by_Weta_Workshops.jpg/revision/latest/scale-to-width-down/630?cb=20150429153010",
                "https://static.wikia.nocookie.net/fastandfurious/images/e/e2/F9.jpg/revision/latest/scale-to-width-down/450?cb=20141023170915",
                "https://static.wikia.nocookie.net/fastandfurious/images/d/d7/F11.jpg/revision/latest/scale-to-width-down/657?cb=20141023170917",
                "https://static.wikia.nocookie.net/fastandfurious/images/b/b2/Furious7_Promo_Still_003.jpg/revision/latest/scale-to-width-down/1000?cb=20150907194912",
                "https://static.wikia.nocookie.net/fastandfurious/images/f/f4/Furious7_Promo_Still_005.jpg/revision/latest/scale-to-width-down/1000?cb=20150907194934",
                "https://static.wikia.nocookie.net/fastandfurious/images/a/a1/Furious7_Promo_Still_008.JPG/revision/latest/scale-to-width-down/1000?cb=20150907200255",
                "https://static.wikia.nocookie.net/fastandfurious/images/1/10/Furious-7-Cars.jpg/revision/latest/scale-to-width-down/1000?cb=20150907201335"),
            rating = "7.1"),

        Movie(id = "8",
            title = "Shang-Chi and The Legend of The Ten Rings",
            year = "2021",
            genre = "Action, Adventure, Fantasy",
            director = "Destin Daniel Cretton",
            actors = "Simu Liu, Awkwafina, Tony Chiu-Wai Leung",
            plot = "Shang-Chi, the master of weaponry-based Kung Fu, is forced to confront his past after being drawn into the Ten Rings organization.",
            poster = "https://terrigen-cdn-dev.marvel.com/content/prod/1x/shangchi_lob_crd_07.jpg",
            images = listOf(
                "https://terrigen-cdn-dev.marvel.com/content/prod/1x_masonry/bus1120_cmp_lum_v0011.1070_r.jpg",
                "https://terrigen-cdn-dev.marvel.com/content/prod/1x_masonry/cpa1380_cmp_ddo_v0140.1111.jpg",
                "https://terrigen-cdn-dev.marvel.com/content/prod/1x_masonry/sbt-25882_r_0.jpg",
                "https://terrigen-cdn-dev.marvel.com/content/prod/1x_masonry/sft1985_cmp_wta_v0414.1180_r.jpg",
                "https://terrigen-cdn-dev.marvel.com/content/prod/1x_masonry/sbt-31998.jpg"),
            rating = "7.4"),

        Movie(id = "9",
            title = "Shershaah",
            year = "2021",
            genre = "Action, Biography, Drama",
            director = "Vishnuvardhan",
            actors = "Sidharth Malhotra, Kiara Advani",
            plot = "The story of PVC awardee Indian soldier Capt. Vikram Batra, who shot to fame and became a household name during the Kargil War in 1999.",
            poster = "https://upload.wikimedia.org/wikipedia/en/9/91/Shershaah_film_poster.jpg",
            images = listOf(
                "https://www.koimoi.com/wp-content/new-galleries/2021/11/sidharth-malhotra-kiara-advani-starrer-shershaah-to-have-world-tv-premiere-001.jpg",
                "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSYaGq70j9XETEqN4GXq8pmccOhSeM4HUzDpQ&usqp=CAU",
                "https://i.ytimg.com/vi/GYelMBQgXIU/maxresdefault.jpg",
                "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQe96CncuY8GapRD9lvGE50EsJogdWdqVUJRw&usqp=CAU",
                "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRJohzzGuDq2jm35GoxIWO4TkCd4SZVOcNNIg&usqp=CAU",
                "https://images.indianexpress.com/2021/07/Shershah-1200.jpg",
                "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTyWwzFLRHCHqR3nPr476p8ZUvaRrFwjgpVnA&usqp=CAU"),
            rating = "8.4"),

        Movie(id = "10",
            title = "Pushpa: The Rise",
            year = "2021",
            genre = "Action, Adventure, Crime",
            director = "Sukumar",
            actors = "Allu Arjun, Rashmika Mandanna",
            plot = "Story of Pushpa Raj, a lorry driver in Seshachalam forests of South India, set in the backdrop of red sandalwood smuggling. Red Sandalwood is endemic to South-Eastern Ghats (mountain range) of India.",
            poster = "https://indiascreen.files.wordpress.com/2022/01/pushpa-tweet.jpg?w=640",
            images = listOf(
                "https://www.koimoi.com/wp-content/new-galleries/2021/12/pushpa-makers-release-a-scene-that-was-deleted-from-the-original-film-001.jpg",
                "https://www.filmcompanion.in/wp-content/uploads/2021/12/Pushpa-Allu-Arjun-1.jpg",
                "https://i.cdn.newsbytesapp.com/images/l256_18601640079810.jpg",
                "https://www.koimoi.com/wp-content/new-galleries/2022/01/see-the-daily-breakdown-of-allu-arjuns-pushpa-001.jpg",
                "https://static.joonsite.com/seelatest/2201101636064059.jpg"),
            rating = "8.2")
    )
}